"""Report generator for markdown daily reports."""

from datetime import datetime, timezone
from pathlib import Path

from loguru import logger

from .ai_summarizer import SummaryResult
from .config import get_settings
from .crawler import CrawlerResult


class ReportGenerator:
    """Generate markdown daily reports."""

    def __init__(self):
        self.settings = get_settings()
        self.reports_dir = Path(self.settings.reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self, crawler_result: CrawlerResult, summary_result: SummaryResult
    ) -> Path:
        """
        Generate a markdown report and save to file.

        Returns:
            Path to the generated report file.
        """
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        filename = self.reports_dir / f"{today}.md"

        content = self._build_report(crawler_result, summary_result, today)

        filename.write_text(content, encoding="utf-8")
        logger.success(f"Report generated: {filename}")

        return filename

    def _build_report(
        self, crawler_result: CrawlerResult, summary_result: SummaryResult, date: str
    ) -> str:
        """Build the markdown report content."""
        lines = [
            f"# GitHub Daily Trends - {date}",
            "",
            f"> 数据来源: {crawler_result.source} | 更新时间: {crawler_result.crawled_at.strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]

        # Table of Contents
        lines.extend(
            [
                "## 📑 目录",
                "",
                "- [🏆 今日精选](#-今日精选)",
                "- [👀 快速浏览](#-快速浏览)",
                "- [📊 统计信息](#-统计信息)",
                "",
            ]
        )

        # Top Picks Section
        lines.extend(
            [
                "## 🏆 今日精选",
                "",
                "以下是今日最值得关注的项目：",
                "",
            ]
        )

        if summary_result.top_picks:
            for summary in summary_result.top_picks:
                lines.append(summary.to_markdown())
        else:
            lines.append("*今日暂无精选项目*\n")

        # Quick Looks Section
        lines.extend(
            [
                "## 👀 快速浏览",
                "",
                "其他值得了解的项目：",
                "",
            ]
        )

        if summary_result.quick_looks:
            for summary in summary_result.quick_looks:
                lines.append(summary.to_markdown())
        else:
            lines.append("*暂无其他项目*\n")

        # Statistics Section
        all_summaries = summary_result.all_summaries
        if all_summaries:
            languages = {}
            total_stars = 0
            for s in all_summaries:
                lang = s.repo.language or "Unknown"
                languages[lang] = languages.get(lang, 0) + 1
                total_stars += s.repo.stars

            top_languages = sorted(languages.items(), key=lambda x: x[1], reverse=True)[:5]

            lines.extend(
                [
                    "## 📊 统计信息",
                    "",
                    f"- **收录项目数**: {len(all_summaries)}",
                    f"- **精选项目数**: {len(summary_result.top_picks)}",
                    f"- **总 Star 数**: {total_stars:,}",
                    f"- **语言分布**: {', '.join(f'{k}({v})' for k, v in top_languages)}",
                    "",
                ]
            )

        # Footer
        lines.extend(
            [
                "---",
                "",
                "*Generated by [GitHub-Daily-Trends-AI](https://github.com/your-repo) 🤖*",
            ]
        )

        return "\n".join(lines)


def generate_report(
    crawler_result: CrawlerResult, summary_result: SummaryResult
) -> Path:
    """Convenience function to generate report."""
    generator = ReportGenerator()
    return generator.generate(crawler_result, summary_result)
